fix: Change the name of printer_settings method to get_printer_settings
When you try to compile tests program, you get this message:

In file included from
/home/runner/work/stl/stl/runtime/tests/dywoq/test.hxx:14, from
/home/runner/work/stl/stl/runtime/tests/main.cxx:1:
/home/runner/work/stl/stl/runtime/tests/dywoq/test/runner.hxx:37:23:
error: declaration of ‘dywoq::test::printer_settings&
dywoq::test::runner::printer_settings()’ changes meaning of
‘printer_settings’ [-Wchanges-meaning] 37 | printer_settings
&printer_settings() noexcept { return printer_settings_; } |
^~~~~~~~~~~~~~~~
/home/runner/work/stl/stl/runtime/tests/dywoq/test/runner.hxx:37:5:
note: used here to mean ‘struct dywoq::test::printer_settings’ 37 |
printer_settings &printer_settings() noexcept { return
printer_settings_; } | ^~~~~~~~~~~~~~~~ In file included from
/home/runner/work/stl/stl/runtime/tests/dywoq/test/category.hxx:8, from
/home/runner/work/stl/stl/runtime/tests/dywoq/test.hxx:8:
/home/runner/work/stl/stl/runtime/tests/dywoq/test/printer.hxx:15:10:
note: declared here 15 | struct printer_settings | ^~~~~~~~~~~~~~~~

Which means the structure and the method with the same name
`printer_settings` collide. To fix this, we change the name to
`get_printer_settings` instead of `printer_settings`